# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
